### ISSUE TITLE
Format for specifying relationships in a group of edges

### ISSUE THREAD

**Issue by maxitg** [maxitg/SetReplace#347]
Requires #346.

### The problem
In studying quantum systems, it is sometimes useful to start from an initial state that is not a `"PureSpaceLike"` collection of edges. We need a way to specify such states.

### Possible solution
A trivial way to specify that would be a full matrix of pairwise relationships between edges, but that's probably not the most efficient way.

Once we have a way to specify that, we can use it for specifying initial states, rule inputs, and even something like `"StatesList"` which could display a list of quantum states over time.

Essentially, this specification of a state is a quantum state in contrast to the simple list of edges, which is the classical state.

### Subtasks
- [ ] Come up with a format (comment in this issue with ideas);
- [ ] Add support for the chosen format for the initial state in `WolframModel`;
- [ ] Add support in the rule inputs;
- [ ] Add support in `"StatesList"`.

**Comment by maxitg** [comment]
This is what Stephen Wolfram calls multi-space.
